// <auto-generated />
using System;
using ContratoTestWebApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContratoTestWebApi.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20221122153850_contrato")]
    partial class contrato
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContratoTestWebApi.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AlicuotaFija")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AlicuotaVariable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AlicuotasVigentes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIIU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnoPedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Deuda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUnidadComercial")
                        .HasColumnType("int");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroContrato")
                        .HasColumnType("int");

                    b.Property<int>("PolizaDigital")
                        .HasColumnType("int");

                    b.Property<decimal>("Prima")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regimen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Siniestros")
                        .HasColumnType("int");

                    b.Property<int>("Trabajadores")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("ContratoTestWebApi.Models.UnidadComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NombreUnidadComercial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnidadComercial");
                });
#pragma warning restore 612, 618
        }
    }
}
